version: 2.1
jobs:
  test_frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
workflows:
  version: 2
  run_test:
    jobs:
      - test_frontend
